sources:
  - name: src
    database: sourcedb
    schema: mk_mall
    tables:
      - name: customers
      - name: regions
      - name: nations
      - name: v_nations
      
      - name: lineitems
      - name: parts
      - name: suppliers
      - name: partsupps

      - name: orders
        config:
          freshness:
            warn_after: {count: 3, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: o_orderdate::timestamp_ntz


  - name: src_1
    database: mkmotors_dev
    schema: staging
    tables:
      - name: stg_employees
      - name: stg_dates